id_width = 16
spatial_hash_key = 'coord'

[components]
coord = { type = '::entity_store_helper::grid_2d::Coord', storage = 'flat' }
solid = { storage = 'hash' }
tile = { type = '::tile::TileInfo', storage = 'btree' }
player = { storage = 'vector' }

[spatial_hash]
solid_count = { component = 'solid', aggregate = 'count' }
